# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 23:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrollmotion', '0002_auto_20170712_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompressedImageTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default=b'', max_length=300)),
                ('name', models.CharField(default=b'', max_length=300)),
                ('size', models.IntegerField(default=0)),
                ('image_type', models.CharField(choices=[(b'jpg', b'jpg'), (b'png', b'png')], default=b'jpg', max_length=5)),
                ('original_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compressedimagetwo', to='scrollmotion.Image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='image',
            name='compressed_two',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='scrollmotion.CompressedImageTwo'),
        ),
    ]
